var expect = require('chai').expect;
var chai = require('chai');
var chaiHTTP = require('chai-http');
const mongoose = require('mongoose');
var schemas = require("../schemas");
var db = require('../db');
var chai = require('chai');
chai.use(require('chai-match'));
chai.use(chaiHTTP);
const server = 'http://localhost:9000';
